 write a python program to generate an array of 15 random number from a standard normal distribution?

In [2]:
import numpy as np

In [3]:
import numpy as np
number = np.random.randn(3,3)
print(number)

[[ 0.88196068  1.13261719  1.90496884]
 [ 1.3493629   0.34111659  0.53053138]
 [-0.49458942  0.00318014 -1.62356896]]
