Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [3]:
import numpy as np

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])